
name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "48 22 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "2739328994@qq.com"
          git config --local user.name "WuuMark"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Regularly update at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
